// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserLogin struct {
	ID        int32            `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	LoginTime pgtype.Timestamp `json:"login_time"`
}
