// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

// append-only event log of user login events.
type UserLogin struct {
	// user identifier - each unique value represents one user.
	UserID int64 `json:"user_id"`
	// provided by the database at insert time; avoid supplying value on insertion
	LoggedInAt time.Time `json:"logged_in_at"`
}
