// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_logins.sql

package queries

import (
	"context"
	"time"
)

const getDailyUniqueUsers = `-- name: GetDailyUniqueUsers :one
SELECT COUNT(DISTINCT user_id)
FROM user_logins
WHERE logged_in_at >= $1
  AND logged_in_at <  $1 + INTERVAL '1 day'
`

func (q *Queries) GetDailyUniqueUsers(ctx context.Context, day time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, getDailyUniqueUsers, day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMonthlyUniqueUsers = `-- name: GetMonthlyUniqueUsers :one
SELECT COUNT(DISTINCT user_id)
FROM user_logins
WHERE logged_in_at >= $1
  AND logged_in_at <  $1 + INTERVAL '1 month'
`

func (q *Queries) GetMonthlyUniqueUsers(ctx context.Context, month time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, getMonthlyUniqueUsers, month)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertUserLogin = `-- name: InsertUserLogin :exec
INSERT INTO user_logins (user_id, logged_in_at)
VALUES ($1, $2)
`

type InsertUserLoginParams struct {
	UserID     int64     `json:"user_id"`
	LoggedInAt time.Time `json:"logged_in_at"`
}

func (q *Queries) InsertUserLogin(ctx context.Context, arg InsertUserLoginParams) error {
	_, err := q.db.Exec(ctx, insertUserLogin, arg.UserID, arg.LoggedInAt)
	return err
}
