// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_analytics.sql

package queries

import (
	"context"
)

const getUserLogins = `-- name: GetUserLogins :many
SELECT id
  , user_id
  , login_time
FROM user_logins
`

func (q *Queries) GetUserLogins(ctx context.Context) ([]UserLogin, error) {
	rows, err := q.db.Query(ctx, getUserLogins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserLogin
	for rows.Next() {
		var i UserLogin
		if err := rows.Scan(&i.ID, &i.UserID, &i.LoginTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
