// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference for this specific occurrence (e.g. trace ID).
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated for this occurrence.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type string `json:"type"`
}

// PostApiV1LoginsJSONBody defines parameters for PostApiV1Logins.
type PostApiV1LoginsJSONBody struct {
	LoginTime time.Time          `json:"login_time"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// PostApiV1LoginsJSONRequestBody defines body for PostApiV1Logins for application/json ContentType.
type PostApiV1LoginsJSONRequestBody PostApiV1LoginsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/livez)
	GetApiLivez(w http.ResponseWriter, r *http.Request)

	// (GET /api/readyz)
	GetApiReadyz(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/analytics/users/daily/{day})
	GetApiV1AnalyticsUsersDailyDay(w http.ResponseWriter, r *http.Request, day openapi_types.Date)

	// (GET /api/v1/analytics/users/monthly/{month})
	GetApiV1AnalyticsUsersMonthlyMonth(w http.ResponseWriter, r *http.Request, month string)

	// (POST /api/v1/logins)
	PostApiV1Logins(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/livez)
func (_ Unimplemented) GetApiLivez(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/readyz)
func (_ Unimplemented) GetApiReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/analytics/users/daily/{day})
func (_ Unimplemented) GetApiV1AnalyticsUsersDailyDay(w http.ResponseWriter, r *http.Request, day openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/analytics/users/monthly/{month})
func (_ Unimplemented) GetApiV1AnalyticsUsersMonthlyMonth(w http.ResponseWriter, r *http.Request, month string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/logins)
func (_ Unimplemented) PostApiV1Logins(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiLivez operation middleware
func (siw *ServerInterfaceWrapper) GetApiLivez(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLivez(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetApiReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AnalyticsUsersDailyDay operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AnalyticsUsersDailyDay(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "day" -------------
	var day openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "day", chi.URLParam(r, "day"), &day, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "day", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AnalyticsUsersDailyDay(w, r, day)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AnalyticsUsersMonthlyMonth operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AnalyticsUsersMonthlyMonth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "month" -------------
	var month string

	err = runtime.BindStyledParameterWithOptions("simple", "month", chi.URLParam(r, "month"), &month, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AnalyticsUsersMonthlyMonth(w, r, month)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Logins operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Logins(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Logins(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/livez", wrapper.GetApiLivez)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/readyz", wrapper.GetApiReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/analytics/users/daily/{day}", wrapper.GetApiV1AnalyticsUsersDailyDay)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/analytics/users/monthly/{month}", wrapper.GetApiV1AnalyticsUsersMonthlyMonth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/logins", wrapper.PostApiV1Logins)
	})

	return r
}

type GetApiLivezRequestObject struct {
}

type GetApiLivezResponseObject interface {
	VisitGetApiLivezResponse(w http.ResponseWriter) error
}

type GetApiLivez200JSONResponse struct {
	Data *string `json:"data,omitempty"`
}

func (response GetApiLivez200JSONResponse) VisitGetApiLivezResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiReadyzRequestObject struct {
}

type GetApiReadyzResponseObject interface {
	VisitGetApiReadyzResponse(w http.ResponseWriter) error
}

type GetApiReadyz200JSONResponse struct {
	Data *string `json:"data,omitempty"`
}

func (response GetApiReadyz200JSONResponse) VisitGetApiReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersDailyDayRequestObject struct {
	Day openapi_types.Date `json:"day"`
}

type GetApiV1AnalyticsUsersDailyDayResponseObject interface {
	VisitGetApiV1AnalyticsUsersDailyDayResponse(w http.ResponseWriter) error
}

type GetApiV1AnalyticsUsersDailyDay200JSONResponse struct {
	Data *int `json:"data,omitempty"`
}

func (response GetApiV1AnalyticsUsersDailyDay200JSONResponse) VisitGetApiV1AnalyticsUsersDailyDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersDailyDay400JSONResponse ErrorResponse

func (response GetApiV1AnalyticsUsersDailyDay400JSONResponse) VisitGetApiV1AnalyticsUsersDailyDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersMonthlyMonthRequestObject struct {
	Month string `json:"month"`
}

type GetApiV1AnalyticsUsersMonthlyMonthResponseObject interface {
	VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w http.ResponseWriter) error
}

type GetApiV1AnalyticsUsersMonthlyMonth200JSONResponse struct {
	Data *int `json:"data,omitempty"`
}

func (response GetApiV1AnalyticsUsersMonthlyMonth200JSONResponse) VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersMonthlyMonth400JSONResponse ErrorResponse

func (response GetApiV1AnalyticsUsersMonthlyMonth400JSONResponse) VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostApiV1LoginsRequestObject struct {
	Body *PostApiV1LoginsJSONRequestBody
}

type PostApiV1LoginsResponseObject interface {
	VisitPostApiV1LoginsResponse(w http.ResponseWriter) error
}

type PostApiV1Logins201Response struct {
}

func (response PostApiV1Logins201Response) VisitPostApiV1LoginsResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PostApiV1Logins400JSONResponse ErrorResponse

func (response PostApiV1Logins400JSONResponse) VisitPostApiV1LoginsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/livez)
	GetApiLivez(ctx context.Context, request GetApiLivezRequestObject) (GetApiLivezResponseObject, error)

	// (GET /api/readyz)
	GetApiReadyz(ctx context.Context, request GetApiReadyzRequestObject) (GetApiReadyzResponseObject, error)

	// (GET /api/v1/analytics/users/daily/{day})
	GetApiV1AnalyticsUsersDailyDay(ctx context.Context, request GetApiV1AnalyticsUsersDailyDayRequestObject) (GetApiV1AnalyticsUsersDailyDayResponseObject, error)

	// (GET /api/v1/analytics/users/monthly/{month})
	GetApiV1AnalyticsUsersMonthlyMonth(ctx context.Context, request GetApiV1AnalyticsUsersMonthlyMonthRequestObject) (GetApiV1AnalyticsUsersMonthlyMonthResponseObject, error)

	// (POST /api/v1/logins)
	PostApiV1Logins(ctx context.Context, request PostApiV1LoginsRequestObject) (PostApiV1LoginsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiLivez operation middleware
func (sh *strictHandler) GetApiLivez(w http.ResponseWriter, r *http.Request) {
	var request GetApiLivezRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLivez(ctx, request.(GetApiLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLivez")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiLivezResponseObject); ok {
		if err := validResponse.VisitGetApiLivezResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiReadyz operation middleware
func (sh *strictHandler) GetApiReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetApiReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiReadyz(ctx, request.(GetApiReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiReadyzResponseObject); ok {
		if err := validResponse.VisitGetApiReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AnalyticsUsersDailyDay operation middleware
func (sh *strictHandler) GetApiV1AnalyticsUsersDailyDay(w http.ResponseWriter, r *http.Request, day openapi_types.Date) {
	var request GetApiV1AnalyticsUsersDailyDayRequestObject

	request.Day = day

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AnalyticsUsersDailyDay(ctx, request.(GetApiV1AnalyticsUsersDailyDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AnalyticsUsersDailyDay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1AnalyticsUsersDailyDayResponseObject); ok {
		if err := validResponse.VisitGetApiV1AnalyticsUsersDailyDayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AnalyticsUsersMonthlyMonth operation middleware
func (sh *strictHandler) GetApiV1AnalyticsUsersMonthlyMonth(w http.ResponseWriter, r *http.Request, month string) {
	var request GetApiV1AnalyticsUsersMonthlyMonthRequestObject

	request.Month = month

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AnalyticsUsersMonthlyMonth(ctx, request.(GetApiV1AnalyticsUsersMonthlyMonthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AnalyticsUsersMonthlyMonth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1AnalyticsUsersMonthlyMonthResponseObject); ok {
		if err := validResponse.VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Logins operation middleware
func (sh *strictHandler) PostApiV1Logins(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1LoginsRequestObject

	var body PostApiV1LoginsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Logins(ctx, request.(PostApiV1LoginsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Logins")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1LoginsResponseObject); ok {
		if err := validResponse.VisitPostApiV1LoginsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
