// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference for this specific occurrence (e.g. trace ID).
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated for this occurrence.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type string `json:"type"`
}

// PostApiV1LoginsJSONBody defines parameters for PostApiV1Logins.
type PostApiV1LoginsJSONBody struct {
	LoginTime time.Time          `json:"login_time"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// PostApiV1LoginsJSONRequestBody defines body for PostApiV1Logins for application/json ContentType.
type PostApiV1LoginsJSONRequestBody PostApiV1LoginsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/livez)
	GetApiLivez(c *gin.Context)

	// (GET /api/readyz)
	GetApiReadyz(c *gin.Context)

	// (GET /api/v1/analytics/users/daily/{day})
	GetApiV1AnalyticsUsersDailyDay(c *gin.Context, day openapi_types.Date)

	// (GET /api/v1/analytics/users/monthly/{month})
	GetApiV1AnalyticsUsersMonthlyMonth(c *gin.Context, month string)

	// (POST /api/v1/logins)
	PostApiV1Logins(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiLivez operation middleware
func (siw *ServerInterfaceWrapper) GetApiLivez(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiLivez(c)
}

// GetApiReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetApiReadyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiReadyz(c)
}

// GetApiV1AnalyticsUsersDailyDay operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AnalyticsUsersDailyDay(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "day" -------------
	var day openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "day", c.Param("day"), &day, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter day: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1AnalyticsUsersDailyDay(c, day)
}

// GetApiV1AnalyticsUsersMonthlyMonth operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AnalyticsUsersMonthlyMonth(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "month" -------------
	var month string

	err = runtime.BindStyledParameterWithOptions("simple", "month", c.Param("month"), &month, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter month: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1AnalyticsUsersMonthlyMonth(c, month)
}

// PostApiV1Logins operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Logins(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Logins(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/livez", wrapper.GetApiLivez)
	router.GET(options.BaseURL+"/api/readyz", wrapper.GetApiReadyz)
	router.GET(options.BaseURL+"/api/v1/analytics/users/daily/:day", wrapper.GetApiV1AnalyticsUsersDailyDay)
	router.GET(options.BaseURL+"/api/v1/analytics/users/monthly/:month", wrapper.GetApiV1AnalyticsUsersMonthlyMonth)
	router.POST(options.BaseURL+"/api/v1/logins", wrapper.PostApiV1Logins)
}

type GetApiLivezRequestObject struct {
}

type GetApiLivezResponseObject interface {
	VisitGetApiLivezResponse(w http.ResponseWriter) error
}

type GetApiLivez200JSONResponse struct {
	Data *string `json:"data,omitempty"`
}

func (response GetApiLivez200JSONResponse) VisitGetApiLivezResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiReadyzRequestObject struct {
}

type GetApiReadyzResponseObject interface {
	VisitGetApiReadyzResponse(w http.ResponseWriter) error
}

type GetApiReadyz200JSONResponse struct {
	Data *string `json:"data,omitempty"`
}

func (response GetApiReadyz200JSONResponse) VisitGetApiReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersDailyDayRequestObject struct {
	Day openapi_types.Date `json:"day"`
}

type GetApiV1AnalyticsUsersDailyDayResponseObject interface {
	VisitGetApiV1AnalyticsUsersDailyDayResponse(w http.ResponseWriter) error
}

type GetApiV1AnalyticsUsersDailyDay200JSONResponse struct {
	Data *int `json:"data,omitempty"`
}

func (response GetApiV1AnalyticsUsersDailyDay200JSONResponse) VisitGetApiV1AnalyticsUsersDailyDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersDailyDay400JSONResponse ErrorResponse

func (response GetApiV1AnalyticsUsersDailyDay400JSONResponse) VisitGetApiV1AnalyticsUsersDailyDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersMonthlyMonthRequestObject struct {
	Month string `json:"month"`
}

type GetApiV1AnalyticsUsersMonthlyMonthResponseObject interface {
	VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w http.ResponseWriter) error
}

type GetApiV1AnalyticsUsersMonthlyMonth200JSONResponse struct {
	Data *int `json:"data,omitempty"`
}

func (response GetApiV1AnalyticsUsersMonthlyMonth200JSONResponse) VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiV1AnalyticsUsersMonthlyMonth400JSONResponse ErrorResponse

func (response GetApiV1AnalyticsUsersMonthlyMonth400JSONResponse) VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostApiV1LoginsRequestObject struct {
	Body *PostApiV1LoginsJSONRequestBody
}

type PostApiV1LoginsResponseObject interface {
	VisitPostApiV1LoginsResponse(w http.ResponseWriter) error
}

type PostApiV1Logins201Response struct {
}

func (response PostApiV1Logins201Response) VisitPostApiV1LoginsResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PostApiV1Logins400JSONResponse ErrorResponse

func (response PostApiV1Logins400JSONResponse) VisitPostApiV1LoginsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/livez)
	GetApiLivez(ctx context.Context, request GetApiLivezRequestObject) (GetApiLivezResponseObject, error)

	// (GET /api/readyz)
	GetApiReadyz(ctx context.Context, request GetApiReadyzRequestObject) (GetApiReadyzResponseObject, error)

	// (GET /api/v1/analytics/users/daily/{day})
	GetApiV1AnalyticsUsersDailyDay(ctx context.Context, request GetApiV1AnalyticsUsersDailyDayRequestObject) (GetApiV1AnalyticsUsersDailyDayResponseObject, error)

	// (GET /api/v1/analytics/users/monthly/{month})
	GetApiV1AnalyticsUsersMonthlyMonth(ctx context.Context, request GetApiV1AnalyticsUsersMonthlyMonthRequestObject) (GetApiV1AnalyticsUsersMonthlyMonthResponseObject, error)

	// (POST /api/v1/logins)
	PostApiV1Logins(ctx context.Context, request PostApiV1LoginsRequestObject) (PostApiV1LoginsResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetApiLivez operation middleware
func (sh *strictHandler) GetApiLivez(ctx *gin.Context) {
	var request GetApiLivezRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLivez(ctx, request.(GetApiLivezRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLivez")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApiLivezResponseObject); ok {
		if err := validResponse.VisitGetApiLivezResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiReadyz operation middleware
func (sh *strictHandler) GetApiReadyz(ctx *gin.Context) {
	var request GetApiReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiReadyz(ctx, request.(GetApiReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiReadyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApiReadyzResponseObject); ok {
		if err := validResponse.VisitGetApiReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AnalyticsUsersDailyDay operation middleware
func (sh *strictHandler) GetApiV1AnalyticsUsersDailyDay(ctx *gin.Context, day openapi_types.Date) {
	var request GetApiV1AnalyticsUsersDailyDayRequestObject

	request.Day = day

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AnalyticsUsersDailyDay(ctx, request.(GetApiV1AnalyticsUsersDailyDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AnalyticsUsersDailyDay")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApiV1AnalyticsUsersDailyDayResponseObject); ok {
		if err := validResponse.VisitGetApiV1AnalyticsUsersDailyDayResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1AnalyticsUsersMonthlyMonth operation middleware
func (sh *strictHandler) GetApiV1AnalyticsUsersMonthlyMonth(ctx *gin.Context, month string) {
	var request GetApiV1AnalyticsUsersMonthlyMonthRequestObject

	request.Month = month

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1AnalyticsUsersMonthlyMonth(ctx, request.(GetApiV1AnalyticsUsersMonthlyMonthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1AnalyticsUsersMonthlyMonth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApiV1AnalyticsUsersMonthlyMonthResponseObject); ok {
		if err := validResponse.VisitGetApiV1AnalyticsUsersMonthlyMonthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Logins operation middleware
func (sh *strictHandler) PostApiV1Logins(ctx *gin.Context) {
	var request PostApiV1LoginsRequestObject

	var body PostApiV1LoginsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Logins(ctx, request.(PostApiV1LoginsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Logins")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PostApiV1LoginsResponseObject); ok {
		if err := validResponse.VisitPostApiV1LoginsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
